version: "3.9"

services:
  db:
    image: postgres:15  # PostgreSQL 15 버전
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"  # PostgreSQL 포트 매핑
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 데이터 영속성을 위한 볼륨

volumes:
  postgres-data:  # PostgreSQL 데이터 볼륨
