
services:
  db:
    image: postgres:15  # PostgreSQL 15 버전
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"  # PostgreSQL 포트 매핑
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 데이터 영속성을 위한 볼륨

  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  # 단일 노드로 실행하도록 설정
      - xpack.security.enabled=false  # X-Pack 보안 기능 비활성화 (SSL/TLS 설정 없이 클러스터에 접근 가능)
      - bootstrap.memory_lock=true  # 메모리 락 활성화 (메모리 스왑 방지)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # JVM 메모리 최소 및 최대 크기 설정
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # HTTP REST API 포트 매핑
      - "9300:9300"  # 노드 간 통신(TCP) 포트 매핑
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data  # 데이터 볼륨(컨테이너 외부에 데이터 저장)

  kibana:
    image: kibana:8.15.3  # Kibana 공식 이미지
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Kibana가 연결할 Elasticsearch 주소
    ports:
      - "5601:5601"  # Kibana 웹 인터페이스 포트
    depends_on:
      - elasticsearch

volumes:
  postgres-data:  # PostgreSQL 데이터 볼륨
  elasticsearch-data:

networks:
  app-network:  # 사용자 정의 네트워크 정의
    driver: bridge
    name: devoka-app-network