name: CI/CD with Gradle

on:
  push:
    branches: [ "dev", "main"] 


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -    name: Checkout
           uses: actions/checkout@v4
        
      -    name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
             java-version: '17'
             distribution: 'temurin'
  
      -    name: Run Test with Gradle
           run: ./gradlew test
          
  deploy:
    if: github.ref == 'refs/heads/main' # main 브런치 일 때만 실행
    runs-on: ubuntu-latest
    steps:
      -    name: Checkout
           uses: actions/checkout@v4
        
      -    name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
             java-version: '17'
             distribution: 'temurin'
            
      -    name: Grant execute permission for gradlew
           run: chmod +x gradlew

      -    name: Clean and Build with Gradle
           run: ./gradlew clean build

      -    name: Copy JAR file to EC2
           uses: appleboy/scp-action@master
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USERNAME }}
             key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
             port: 22
             source: build/libs/devoka-0.0.1-SNAPSHOT.jar
             target: /home/ubuntu/project/

      -    name: Deploy EC2
           uses: appleboy/ssh-action@master
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USERNAME }}
             key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
             port: 22
             script: |
               pkill -f '/home/ubuntu/project/devoka-0.0.1-SNAPSHOT.jar'
               cd /home/ubuntu/project
               nohup java -jar -Dspring.profiles.active=prod devoka-0.0.1-SNAPSHOT.jar &
  
