name: CI/CD with Gradle

on:
  push:
    branches: [ "dev", "main"] 


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -    name: Checkout
           uses: actions/checkout@v4
        
      -    name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
             java-version: '17'
             distribution: 'temurin'
  
      -    name: Run Test with Gradle
           run: ./gradlew test
          
  deploy:
    if: github.ref == 'refs/heads/main' # main 브런치 일 때만 실행
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      -    name: Checkout
           uses: actions/checkout@v4

      -    name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
             java-version: '17'
             distribution: 'temurin'
             
      -    name: Change Directory AND Run deploy script
           run: | 
             echo "현재 작업 디렉토리 : "
             pwd
             
             chmod +x /home/ubuntu/deploy.sh
             export DB_URL=${{ secrets.DB_URL }}
             export DB_USERNAME=${{ secrets.DB_USERNAME }}
             export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
             export CORS_ALLOW_ORIGIN=${{ secrets.CORS_ALLOW_ORIGIN }}
             export CORS_ALLOW_METHOD=${{ secrets.CORS_ALLOW_METHOD }}
             export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
             
             /home/ubuntu/deploy.sh

             echo "최근 애플리케이션 로그 확인:"
             tail -n 50 /home/ubuntu/project/test/app.log

             echo "애플리케이션 상태 확인:"
             curl -I http://localhost:8080 || echo "Application is not responding!"

      # -    name: Check Application Logs
      #      run: |


      # -   name: Test Application
      #     run: |
            
